<?php

namespace Dirigendo\FrontEndBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ServiceTilesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Dirigendo\FrontEndBundle\Controller\ServiceTilesController();
        return $instance;
    }
}
