<?php

namespace Neutron\DataGridBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DataGridController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Neutron\DataGridBundle\Controller\DataGridController();
        return $instance;
    }
}
