parameters:
#    dirigendo_back_end.example.class: Dirigendo\BackEndBundle\Example

services:
#    dirigendo_back_end.example:
#        class: %dirigendo_back_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
